heat_template_version: 2016-10-14

description: HEAT - create webserver 

resources:
  WEBSERVER:
    type: OS::Nova::Server
    properties:
      # Paires de clés
      key_name: axel-key
      # Nom de l'image dans openstack
      image: ct8.4
      # Taille de la VM définit dans openstack
      flavor: m1.medium
      # Choix du réseau
      networks:
        - network: int_net
      # Choix du groupe de sécurité (ici on a allow 22 et 80)
      security_groups:
        - ssh_ping
      name: webserver-axel
      user_data: |
        #!/bin/bash
        yum install httpd
        systemctl enable httpd
        systemctl start httpd

        # Partitionnement et formatage du disque dur
        echo -e "o\nn\np\n1\n\n\nw" | fdisk /dev/vdb
        mkfs.ext4 /dev/vdb1
        echo '/dev/vdb1 /var/www/html ext4 defaults 0 0' >> /etc/fstab
        mount /var/www/html

        # Remplacement de l'index.html par un index personnalisé
        curl http://10.23.108.44/index.html -o /var/www/html/index.html


